#cloud-config
runcmd:
  - apt-get update
  - apt-get install -y openjdk-11-jdk
  - wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.62/bin/apache-tomcat-9.0.62.tar.gz
  - tar xzvf apache-tomcat-9.0.62.tar.gz -C /opt/
  - mv /opt/apache-tomcat-9.0.62 /opt/tomcat
  - useradd -r -m -U -d /opt/tomcat -s /bin/false tomcat
  - chown -R tomcat: /opt/tomcat
  - chmod +x /opt/tomcat/bin/*.sh
  - echo "[Unit]
    Description=Apache Tomcat Web Application Container
    After=network.target
    [Service]
    Type=forking
    Environment=JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
    Environment=CATALINA_HOME=/opt/tomcat
    Environment=CATALINA_BASE=/opt/tomcat
    ExecStart=/opt/tomcat/bin/startup.sh
    ExecStop=/opt/tomcat/bin/shutdown.sh
    User=tomcat
    Group=tomcat
    UMask=0007
    RestartSec=10
    Restart=always
    [Install]
    WantedBy=multi-user.target" > /etc/systemd/system/tomcat.service
  - systemctl daemon-reload
  - systemctl start tomcat
  - systemctl enable tomcat